New project structure
SimulationEverywhere/cadmium_v2 pull request #26
Opened 2023-09-16 18:47 UTC by Jeg27

Replaced the example/MSP432P401R folder with example/rt_msp432.  The new folder has 4 examples which can be used both in the terminal and in Code Composer Studio.  There are also diagram images added for the 4 examples.

2023-09-17 18:10 UTC, romancardenas commented
Hi, @Jeg27 ! The reference branch is `dev-rt`. Please, modify the destination branch and I'll take a look

2023-09-18 14:08 UTC, Jeg27 commented
@romancardenas done!

2023-09-18 16:03 UTC, epecker commented on include/cadmium/simulation/rt_clock/mbedclock.hpp
@romancardenas they seem to be OK. I wonder where those changes come from because these changes were solved in a previous commit.

2023-09-27 08:10 UTC, romancardenas requested changes
It seems like you cloned cadmium inside example/rt_msp432. I'm 100% sure that there is a way to tell your IDE where the original Cadmium is and avoid this. Note that, if we merge your PR as is, anyone downloading the original repo would download all the source code twice, which would lead into longer download times etc.

I saw that now the priority is documentation, that's great. But please, if you have some time try to tackle this issue ASAP.

Great job, by the way!

2023-09-27 08:13 UTC, romancardenas commented
So, just to have a greater picture of the issue:
- Users may download this cadmium repo in any folder of their system
- Then, when creating a new project for the MSP board, they would just need to tell the compiler and the linker where the Cadmium library is. Usually, IDEs allow you to do this in the preferences of the project.

You don't need it to be part of the project, but leave the compiler/linker do the work for you.

2023-10-03 08:51 UTC, romancardenas commented
@Jeg27 any news on this?

2023-10-05 01:22 UTC, Jeg27 commented
I've deleted the duplicate folder.  I will make a note in the future documentation of how to include the cadmium folder within Code Composer Studio.

2023-10-05 07:35 UTC, romancardenas approved these changes
LGTM

2023-10-05 07:35 UTC, merged